### PR TITLE
Basic URL rule, which contains domain name, blocks WS #528

### PR DESCRIPTION
**Pull request by Mizzick**
#528

### CODE REVIEW

**Comment by atropnikov** [comment]
Don't merge until #599 will be accepted

**Comment by ameshkov** [comment]
Guys, this pull request brings inconsistency into the filtering log, please do it right

**Comment by Mizzick** [comment]
Should we remove domain name from the log?

**Comment by ameshkov** [comment]
You should  remove `websocketCheckLogUrl` and log `websocketCheckUrl` only.

However, don't hurry, there is a similar, but more precise request in another pull request:
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/599#discussion_r108074301

**Pull request merged**
