### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by yigido**
I am the native speaker of Turkish, I saw some mistakes in tr localization and I just corrected them.
Please use them for the next release to let me check
Thanks

### CODE REVIEW

**Comment by adguard** [comment]
Hi, thank you! Would you like to get access to our localization webapp (oneskyapp)?

**Comment by yigido** [comment]
It is Ok for me :)
By the way I made a mistake in correction, how can I fix it?

**Comment by adguard** [comment]
Then send me your email, I'll send an invite.

It's better to do all localization there, in oneskyapp.
It is imported automatically from there.

**Comment by yigido** [comment]
Please take it : bekirucarci@yandex.com
after you got my mail, please remove it here or tell me I will remove it in this post 
 I do not want spam.
Thank you.

**Comment by yigido** [comment]
Hello,

I got your e-mail and I just logged in.
There are Chrome Store and extension localizations. It is good.
I will look it in detail. I have an exam now, I have to go :) Wish me luck.

Sincerely,
Bekir

10.04.2015, 12:21, "adguard" <notifications@github.com>:
> Hi! I've sent you invitation, please check it
>
> —
> Reply to this email directly or view it on GitHub.

---
COMODO PROTECTS MY COMPUTER.
https://tr.comodo.com/free-products

**Comment by adguard** [comment]
Good luck:)

Closing this issue for now.

**Pull request closed without merging**
