### PR TITLE
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/201 fix

### PR DESCRIPTION
**Pull request by Mizzick**

### CODE REVIEW

**Comment by atropnikov** [comment]
I don't think that this is a right decision to change 'about' protocol to https. I think is Firefox bug

**Comment by ameshkov** [comment]
Hm, let's check it in the latest nightly then.

**Comment by ameshkov** [comment]
The same issue in the latest alpha.

@atropnikov any idea what can be done about it instead of what's done now?

```Blocked loading mixed active content "about:adg-intercept?402476564841"[Learn More]RemoteAddonsChild.jsm:283:22
: Component returned failure code: 0x805e0006 [nsIContentSecurityManager.performSecurityCheck]
```

**Comment by Mizzick** [comment]
there is no difference really in this point. These requests gonna be intercepted.

**Pull request merged**
