### PR TITLE
Feature/issues/789 User filter syntax highlight

### PR DESCRIPTION
**Pull request by Mizzick**
#789

### CODE REVIEW

**Comment by Mizzick** [comment]
In ace.js

**Comment by atropnikov** [comment]
I've seen only regular expressions. Could we apply colors from the issue?

**Comment by Mizzick** [comment]
maybe it's possible, but it's too difficult to add tokens, so anyway it
gonna look bad

**Comment by ameshkov** [comment]
Let's then use CodeMirror instead of Ace, no problems with adding colors there

**Comment by Mizzick** [comment]
Updated colors

**Pull request merged**
