### PR TITLE
#388 Support remote script rules for non-amo FF

### PR DESCRIPTION
**Pull request by Mizzick**
#388

### CODE REVIEW

**Comment by Mizzick** [comment]
@atropnikov I don't think it's a good idea, local/remote property could be used somewhere else.

**Comment by ameshkov** [comment]
@Mizzick any update on this?

**Comment by ameshkov** [comment]
Or is this pull request redundant and we should close it?

**Comment by Mizzick** [comment]
@ameshkov we can merge it later, then we will be not in hurry for amo review.

**Comment by ameshkov** [comment]
With what @atropnikov does in v2.6 this pull request became redundant.

**Pull request closed without merging**
